//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetails
    {
        public int BookingId { get; set; }
        public int RegId { get; set; }
        public int BusId { get; set; }
        public int Schedule { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string IdProof { get; set; }
        public int SeatNo { get; set; }
    
        public virtual BusDetails BusDetails { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual ScheduleDetails ScheduleDetails { get; set; }
    }
}
