//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleDetails()
        {
            this.BookingDetails = new HashSet<BookingDetails>();
        }
    
        public int ScheduleId { get; set; }
        public int BusId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan DepartTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public int Fare { get; set; }
        public int BookedSeats { get; set; }
        public int AvailableSeats { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
    
        public virtual BusDetails BusDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetails> BookingDetails { get; set; }
    }
}
