//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int RegId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EmailId { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
